"""markdown + latex emitters for the tabular values behind step4 figures.

every step4 figure gets a sibling {stem}.md and {stem}.tex holding exactly the
numbers drawn in the plot. a file is a list of sections; each section is one
table: (title, header, rows) with pre-formatted string cells.

    from ex.utils.tables import fmt_pm, fmt_iqr, write_tables
    rows = [[m] + [fmt_pm(mean[m][i], se[m][i]) for i in range(n)] for m in methods]
    write_tables(stem, [(title, ['Method'] + cols, rows)])

cells use ascii '+/-'; the tex writer maps it to $\\pm$ and escapes '_'.
"""
from __future__ import annotations

import os

import numpy as np


def fmt_pm(mean, err) -> str:
    """'mean +/- err' with 3 sig figs; '--' if mean is not finite."""
    if not np.isfinite(mean):
        return '--'
    if err is None or not np.isfinite(err):
        return f'{mean:.3g}'
    return f'{mean:.3g} +/- {err:.3g}'


def fmt_iqr(med, lo, hi) -> str:
    """'med [lo, hi]' with 3 sig figs; '--' if med is not finite."""
    if not np.isfinite(med):
        return '--'
    if lo is None or hi is None or not (np.isfinite(lo) and np.isfinite(hi)):
        return f'{med:.3g}'
    return f'{med:.3g} [{lo:.3g}, {hi:.3g}]'


def _tex_escape(s: str) -> str:
    """escape underscores and map the ascii '+/-' to math \\pm."""
    return s.replace('_', r'\_').replace('+/-', r'$\pm$')


def _md_section(title, header, rows) -> str:
    lines = [f'## {title}', '']
    lines.append('| ' + ' | '.join(header) + ' |')
    lines.append('|' + '|'.join(['---'] * len(header)) + '|')
    for r in rows:
        lines.append('| ' + ' | '.join(r) + ' |')
    lines.append('')
    return '\n'.join(lines)


def _tex_section(title, header, rows) -> str:
    ncol = len(header)
    lines = [
        r'\begin{table}[ht]',
        r'\centering',
        f'\\caption{{{_tex_escape(title)}}}',
        r'\begin{tabular}{l' + ' r' * (ncol - 1) + '}',
        r'\toprule',
        ' & '.join(_tex_escape(h) for h in header) + r' \\',
        r'\midrule',
    ]
    for r in rows:
        lines.append(' & '.join(_tex_escape(c) for c in r) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(lines)


def write_tables(stem, sections) -> None:
    """write {stem}.md and {stem}.tex from sections = [(title, header, rows)].

    header is a list of column names (first is the row-label column); rows are
    lists of pre-formatted string cells, same length as header.
    """
    os.makedirs(os.path.dirname(stem) or '.', exist_ok=True)
    with open(f'{stem}.md', 'w') as f:
        f.write('\n'.join(_md_section(*s) for s in sections))
    with open(f'{stem}.tex', 'w') as f:
        f.write('% auto-generated by step4; values exactly as plotted\n')
        f.write('\n'.join(_tex_section(*s) for s in sections))
    print(f'  saved {os.path.basename(stem)}.{{md,tex}}')
