"""Trial-union utility (Part 2).

Merges trial_*.json files from multiple source directories into a single
<experiment>_combined/ directory, deduplicating on
    (pilot_variant, hyperparams_json, eval_sample_seed).

When duplicates are found the copy with the better (lower) score is kept.

The combined directory mirrors the normal experiment layout and can be passed
directly to analyze.py as --data-root.

Also writes <exp>_combined/overlap_report.json describing:
  • per-source trial counts per method
  • number of trials shared between sources (deduped)
  • eval_sample_seed values seen (to confirm cell-sampling was seeded)
  • note on HPO seeding (trial configs are deterministic by trial_id)

Usage:
    cd /home/yizhoulu/dpe-submission
    # single source (just re-layout your own data into *_combined/)
    python -m ex.analysis.combine \\
        --experiment smodice_eldr_estimation \\
        --sources /data/user_data/yizhoulu/dpe-submission

    # merge two sources
    python -m ex.analysis.combine \\
        --experiment smodice_eldr_estimation \\
        --sources /data/user_data/yizhoulu/dpe-submission \\
                  /data/user_data/yizhoulu/dpe-submission/mnist_eldr_estimation_avi \\
        --output-root /data/user_data/yizhoulu/dpe-submission
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from .utils import is_method_dir


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dedup_key(trial: dict) -> tuple:
    """Unique identity of a trial: (variant, hyperparams_json, eval_seed).

    Two trials with the same key are considered identical runs.  We keep the
    one with the better (lower) score.

    Note on seeding:
      • eval_sample_seed is stored in every trial JSON (confirmed = 1729 for
        all existing runs).  This means eval-cell sampling IS seeded and
        identical across watchdog invocations.
      • HPO configs are generated by gen_config(registry, method, trial_id),
        which uses trial_id as the RNG seed.  So identical (trial_id, method,
        search-space) → identical hyperparams.  We use hyperparams_json
        directly so we are robust to search-space changes between runs.
    """
    hp_json = json.dumps(trial.get("hyperparams", {}), sort_keys=True)
    return (
        trial.get("pilot_variant", "broad"),
        hp_json,
        trial.get("eval_sample_seed"),
    )


def _load_raw(method_dir: Path, variant: str) -> list[tuple[Path, dict]]:
    d = method_dir / variant
    if not d.exists():
        return []
    pairs: list[tuple[Path, dict]] = []
    for f in sorted(d.glob("trial_*.json")):
        try:
            pairs.append((f, json.loads(f.read_text())))
        except (json.JSONDecodeError, OSError):
            pass
    return pairs


# ---------------------------------------------------------------------------
# Core combine logic
# ---------------------------------------------------------------------------

def combine_experiment(
    experiment: str,
    sources: list[Path],
    output_root: Path,
) -> dict:
    """Merge *experiment* data from *sources* → *output_root*/<exp>_combined/.

    Returns the overlap report dict.
    """
    combined_dir = output_root / f"{experiment}_combined"
    combined_dir.mkdir(parents=True, exist_ok=True)

    print(f"[{experiment}]  {len(sources)} source(s) → {combined_dir}")

    # Collect all method names across all sources.
    all_methods: set[str] = set()
    for src in sources:
        exp_dir = src / experiment
        if not exp_dir.exists():
            print(f"  SKIP (not found): {exp_dir}")
            continue
        for d in exp_dir.iterdir():
            if is_method_dir(d):
                all_methods.add(d.name)

    overlap_report: dict = {
        "experiment": experiment,
        "sources": [str(s) for s in sources],
        "seeding_notes": {
            "eval_sample_seed": (
                "All observed trials use eval_sample_seed=1729; "
                "eval-cell sampling is fully seeded and reproducible."
            ),
            "hpo_seed": (
                "HPO configs are generated deterministically by trial_id via "
                "gen_config(registry, method, trial_id).  "
                "Trials with the same trial_id and search-space produce the "
                "same hyperparams.  We deduplicate on hyperparams_json to be "
                "robust to search-space recalibrations between runs."
            ),
        },
        "methods": {},
    }

    for method in sorted(all_methods):
        # key → (source_label, trial_dict)  — best score wins
        key_to_best: dict[tuple, tuple[str, dict]] = {}
        key_to_sources: dict[tuple, list[str]] = defaultdict(list)
        per_source_counts: dict[str, int] = {}

        for src in sources:
            src_label = src.name
            mdir = src / experiment / method
            if not mdir.exists():
                continue

            n = 0
            for variant in ("broad", "refined"):
                for _, trial in _load_raw(mdir, variant):
                    key = _dedup_key(trial)
                    key_to_sources[key].append(src_label)
                    score = trial.get("score", float("inf"))
                    if key not in key_to_best:
                        key_to_best[key] = (src_label, trial)
                    else:
                        prev_score = key_to_best[key][1].get("score", float("inf"))
                        if score < prev_score:
                            key_to_best[key] = (src_label, trial)
                    n += 1
            per_source_counts[src_label] = n

        n_common = sum(1 for v in key_to_sources.values() if len(set(v)) > 1)
        eval_seeds = sorted(
            {t.get("eval_sample_seed")
             for _, t in key_to_best.values()
             if t.get("eval_sample_seed") is not None}
        )

        overlap_report["methods"][method] = {
            "per_source": per_source_counts,
            "total_unique_trials": len(key_to_best),
            "deduplicated_count": n_common,
            "eval_sample_seeds_seen": eval_seeds,
        }

        # Write combined trials, re-indexed from 0.
        broad_out = combined_dir / method / "broad"
        refined_out = combined_dir / method / "refined"
        broad_out.mkdir(parents=True, exist_ok=True)
        refined_out.mkdir(parents=True, exist_ok=True)

        broad_idx = refined_idx = 0
        for _, (_, trial) in sorted(key_to_best.items()):
            variant = trial.get("pilot_variant", "broad")
            if variant == "refined":
                out_f = refined_out / f"trial_{refined_idx}.json"
                refined_idx += 1
            else:
                out_f = broad_out / f"trial_{broad_idx}.json"
                broad_idx += 1
            out_f.write_text(json.dumps(trial, indent=2))

        print(
            f"  {method:<35} "
            f"broad={broad_idx:>4}  refined={refined_idx:>3}  "
            f"deduped={n_common}"
        )

    report_path = combined_dir / "overlap_report.json"
    report_path.write_text(json.dumps(overlap_report, indent=2))
    print(f"\nOverlap report : {report_path}")
    print(f"Combined dir   : {combined_dir}")
    print(
        "\nTo run analysis on the combined data:\n"
        f"  python -m ex.analysis.analyze "
        f"--experiment {experiment}_combined "
        f"--data-root {output_root}"
    )
    return overlap_report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Union HPO trial results from multiple source directories",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--experiment",
        required=True,
        help="Experiment name (e.g. smodice_eldr_estimation)",
    )
    parser.add_argument(
        "--sources",
        nargs="+",
        required=True,
        help=(
            "One or more root directories, each containing an "
            "<experiment>/ subdirectory with method folders."
        ),
    )
    parser.add_argument(
        "--output-root",
        default="/data/user_data/yizhoulu/dpe-submission",
        help=(
            "Root directory where <experiment>_combined/ will be created "
            "(default: %(default)s)"
        ),
    )
    args = parser.parse_args()

    combine_experiment(
        experiment=args.experiment,
        sources=[Path(s) for s in args.sources],
        output_root=Path(args.output_root),
    )


if __name__ == "__main__":
    main()
