"""tables for the decoupled cells (N = 8192, N* swept): eldr error, pointwise mae, regret.

    processed_results/two_leg_q{p}_N8192[_ns{N*}].h5
      --> figures/dokls_dec_{eldr_err,pointwise_mae,regret}_table.{md,tex}
per (p*, N*): a mean +/- se section and a median [q1, q3] section, one row per
method in the appendix order, one column per kl. cells use ex.utils.tables
(3 significant figures), the same format as the step4 tables.

usage: python -m ex.ablations.dokls.dec_tables
"""
import os

import h5py

from ex.ablations.dokls.variants import resolve
from ex.utils.tables import fmt_iqr, fmt_pm

ROWS = [('BDRE', 'BDRE'), ('MultiHeadTDRE', 'TDRE'), ('TSM', 'TSM'), ('CTSM', 'CTSM'),
        ('VFM', 'VFM'), ('FMDRE', 'FMDRE'), ('BDRE_NWJ', 'BDRE_NWJ'),
        ('BDRE_DV', 'BDRE_DV'), ('MHT_NWJ', 'TDRE_NWJ'), ('MHT_DV', 'TDRE_DV')]
METRICS = {
    'eldr_err': ('eldr_err_mean', 'eldr_err_se', ('eldr_err_med', 'eldr_err_q1',
                 'eldr_err_q3'), 'Absolute ELDR error, mean $\\pm$ SE'),
    'pointwise_mae': ('mae', 'mae_se', ('mae_med', 'mae_q1', 'mae_q3'),
                      'Pointwise LDR MAE, mean $\\pm$ SE'),
    'regret': ('regret_mean', 'regret_se', ('regret_mean', 'regret_q1', 'regret_q3'),
               'Relative regret, median $\\pm$ bootstrap SE'),
}
NSTARS = [2048, 4096, 8192]


def cell_file(proc, p, ns):
    """processed file of the decoupled cell (p*, N*) at N = 8192."""
    return os.path.join(proc, f"two_leg_q{p}_N8192{'' if ns == 8192 else f'_ns{ns}'}.h5")


def sections(proc, metric):
    """[(caption, rows)] for one metric: per (p*, N*) a mean/se and an iqr section."""
    mean_k, se_k, iqr_k, title = metric
    out = []
    for p in (0, 1):
        for ns in NSTARS:
            with h5py.File(cell_file(proc, p, ns), 'r') as f:
                def get(key, m):
                    return f[f'{key}_two_leg_{m}_{p}_8192'][:]
                pm = [[name] + [fmt_pm(a, b) for a, b in zip(get(mean_k, m), get(se_k, m))]
                      for m, name in ROWS]
                iq = [[name] + [fmt_iqr(*v) for v in zip(*(get(k, m) for k in iqr_k))]
                      for m, name in ROWS]
            where = f'$p_* = q_{p}$, $N_* = {ns}$'
            out += [(f'{title} -- {where}', pm), (f'{title} (median [q1, q3]) -- {where}', iq)]
    return out


def write(stem, header, secs):
    """{stem}.md and {stem}.tex from [(caption, rows)]; tex cells escape '_' and '+/-'."""
    def esc(c):
        return c.replace('_', r'\_').replace('+/-', r'$\pm$')
    tex = ['% generated by ex/ablations/dokls/dec_tables.py from processed_results '
           '(decoupled N=8192 cells)']
    md = []
    for cap, rows in secs:
        tex += [r'\begin{table}[ht]', r'\centering', rf'\caption{{{cap}}}',
                r'\begin{tabular}{l' + ' r' * (len(header) - 1) + '}', r'\toprule',
                ' & '.join(header) + r' \\', r'\midrule']
        tex += [' & '.join(esc(c) for c in r) + r' \\' for r in rows]
        tex += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
        md += [f'## {cap}', '', '| ' + ' | '.join(header) + ' |',
               '|' + '|'.join(['---'] * len(header)) + '|']
        md += ['| ' + ' | '.join(r) + ' |' for r in rows] + ['']
    with open(f'{stem}.md', 'w') as f:
        f.write('\n'.join(md))
    with open(f'{stem}.tex', 'w') as f:
        f.write('\n'.join(tex))
    print(f'  saved {os.path.basename(stem)}.{{md,tex}}')


def main():
    """write the three decoupled-cell tables into figures_dir."""
    _, _, cfg = resolve('q0_N8192', 'two_leg')
    header = ['Method'] + [f'KL={k:g}' for k in cfg['kl_distances']]
    for name, metric in METRICS.items():
        write(os.path.join(cfg['figures_dir'], f'dokls_dec_{name}_table'), header,
              sections(cfg['processed_results_dir'], metric))


if __name__ == '__main__':
    main()
