"""generate the per-variant config yamls the dokls downstream expects.

variants.config_path(tag, route) points at configs/dokls_<route>_<tag>.yaml, but
nothing writes those files: the HPO campaign never touched them (it goes through
the StudyConfig modules), so the gap only surfaces at variants.resolve() -- i.e.
in assemble_winners and step2/3/4.

each generated file is the base config.yaml with that variant's selection pinned:
  route     <- route
  pstar_idx <- VARIANTS[tag][0]
  nsamples  <- VARIANTS[tag][1]   (N, p0/p1 budget)
  nstar     <- VARIANTS[tag][2]   (Nstar, p* budget)

env placeholders such as ${DPE_DATA_ROOT} are copied VERBATIM. this is why the
base config is edited as TEXT rather than load->dump: src.utils.io monkey-patches
yaml.safe_load to expandvars, so a round-trip would bake cluster-absolute paths
into a public-repo config (see the no-cluster-paths-in-configs rule).

usage:
  python -m ex.ablations.dokls.make_variant_configs
  python -m ex.ablations.dokls.make_variant_configs --route two_leg
"""
import argparse
import re
from pathlib import Path

from ex.ablations.dokls import variants

# keys pinned per variant; each already exists as a scalar line in config.yaml
_PINNED = ("route", "pstar_idx", "nsamples", "nstar")


def _pin(text: str, key: str, value) -> str:
    """replace the scalar line `key: ...` in yaml text, preserving everything else."""
    pat = re.compile(rf"^{re.escape(key)}:.*$", re.M)
    if not pat.search(text):
        raise KeyError(f"key {key!r} not found in base config.yaml")
    return pat.sub(f"{key}: {value}", text, count=1)


def main(route: str | None = None, force: bool = False) -> None:
    """write configs/dokls_<route>_<tag>.yaml for every (tag, route) pair.

    procedure: read base config.yaml as text -> for each tag x route, pin
    {route, pstar_idx, nsamples} by line substitution -> write config_path(tag, route).

    args:
        route: only emit this route; None emits all of variants.ROUTES.
        force: overwrite existing files (default: skip them).
    """
    base_dir = Path(__file__).resolve().parent
    base_text = (base_dir / "config.yaml").read_text()
    banner = "# GENERATED by make_variant_configs.py -- edit config.yaml, not this file.\n"

    routes = variants.ROUTES if route is None else [route]
    written, skipped = [], []
    for r in routes:
        for tag, (pstar_idx, nsamples, nstar) in variants.VARIANTS.items():
            out = variants.config_path(tag, r)
            out.parent.mkdir(parents=True, exist_ok=True)
            if out.exists() and not force:
                skipped.append(out.name)
                continue
            text = base_text
            for key, val in zip(_PINNED, (r, pstar_idx, nsamples, nstar)):
                text = _pin(text, key, val)
            out.write_text(banner + text)
            written.append(out.name)

    print(f"wrote {len(written)} config(s); skipped {len(skipped)} existing")
    for n in written:
        print(f"  + {n}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=main.__doc__)
    p.add_argument("--route", default=None, choices=variants.ROUTES,
                   help="only emit this route; omit for all")
    p.add_argument("--force", action="store_true", help="overwrite existing")
    args = p.parse_args()
    main(args.route, args.force)
