methods:
  BDRE:
    hyperparams:
      n_steps: 6400
      learning_rate: 0.0006631351425139251
      latent_dim: 64
      batch_size: 256
      weight_decay: 0.001
      n_hidden_layers: 5
    score:
      best_value_median: 11.355743408203125
      winner_trial_number: 532
      best_step: -1
      source: hpo_holdout_global
  BDRE_NWJ:
    hyperparams:
      n_steps: 6400
      lr: 0.00010279885784721849
      latent_dim: 64
      batch_size: 64
      weight_decay: 0.0
      n_hidden_layers: 5
    score:
      best_value_median: 8.119958400726318
      winner_trial_number: 2142
      best_step: -1
      source: hpo_holdout_global
  BDRE_DV:
    hyperparams:
      n_steps: 6400
      lr: 0.00029734940821570015
      latent_dim: 64
      batch_size: 128
      weight_decay: 0.0
      n_hidden_layers: 5
    score:
      best_value_median: 35.58016490936279
      winner_trial_number: 693
      best_step: -1
      source: hpo_holdout_global
  MultiHeadTDRE:
    hyperparams:
      n_steps: 6400
      learning_rate: 0.026048675384537843
      hidden_dim: 256
      head_dim: 40
      num_shared_layers: 1
      num_waypoints: 5
      batch_size: 64
      weight_decay: 0.0001
      n_hidden_layers: 5
    score:
      best_value_median: 6.584018707275391
      winner_trial_number: 2107
      best_step: -1
      source: hpo_holdout_global
  MHT_NWJ:
    hyperparams:
      n_steps: 6400
      lr: 0.00010828664903870338
      latent_dim: 64
      num_waypoints: 5
      batch_size: 512
      weight_decay: 1.0e-05
      n_hidden_layers: 5
    score:
      best_value_median: 9.556275844573975
      winner_trial_number: 735
      best_step: -1
      source: hpo_holdout_global
  MHT_DV:
    hyperparams:
      n_steps: 6400
      lr: 0.0001259394121989966
      latent_dim: 64
      num_waypoints: 15
      batch_size: 64
      weight_decay: 0.0
      n_hidden_layers: 5
    score:
      best_value_median: 12.052065372467041
      winner_trial_number: 1155
      best_step: -1
      source: hpo_holdout_global
  CTSM:
    hyperparams:
      n_steps: 6400
      lr: 0.019504080759711308
      batch_size: 512
      sched: stiff
      inner_eps: 0.0
      time_dist: stiff_10
      k: 10
      gamma_min: 0.1148817043497977
      apply_iw: true
      sigma: 0.5566885085191455
      eps: 0.004865110002372926
      integration_steps: 2600
      test_eps: 0.004852211155469044
      hidden_dim: 32
      activation: silu
      reweight: true
      ema_decay: null
      grad_clip_norm: 5.0
      weight_decay: 0.0001
      cosine_min_factor: 0.0
      test_sched: stiff
      test_sigma: 0.5566885085191455
      test_inner_eps: 0.0
      test_gamma_min: 0.1148817043497977
      test_k: 10
      n_hidden_layers: 5
    score:
      best_value_median: 11.014982223510742
      winner_trial_number: 1050
      best_step: -1
      source: hpo_holdout_global
  TSM:
    hyperparams:
      n_steps: 6400
      lr: 0.005264278626199804
      batch_size: 512
      time_dist: uniform
      eps: 0.0040631233171043064
      integration_steps: 1200
      hidden_dim: 64
      activation: elu
      reweight: true
      ema_decay: 0.9999
      grad_clip_norm: 5.0
      weight_decay: 0.0001
      cosine_min_factor: 0.0
      n_hidden_layers: 5
    score:
      best_value_median: 13.803567886352539
      winner_trial_number: 1071
      best_step: -1
      source: hpo_holdout_global
  VFM:
    hyperparams:
      n_steps: 6400
      lr: 0.0010026411874671302
      batch_size: 128
      sched: stiff
      inner_eps: 0.0
      precond: true
      div_method: exact
      div_noise: rademacher
      n_hutch_samples: 4
      activation: silu
      k: 80
      gamma_min: 0.0
      eps: 0.00012353282548756365
      integration_steps: 1200
      ema_decay: 0.999
      grad_clip_norm: 5.0
      sigma: 0.28864947019913173
      test_eps: 0.0003462985832886523
      hidden_dim: 512
      weight_decay: 0.001
      time_dist: beta_5_5
      layernorm: 'off'
      antithetic: true
      cosine_min_factor: 0.0
      apply_iw: true
      test_sched: stiff
      test_sigma: 0.28864947019913173
      test_inner_eps: 0.0
      test_gamma_min: 0.0
      test_k: 80
      n_hidden_layers: 5
    score:
      best_value_median: 1.5615238547325134
      winner_trial_number: 518
      best_step: -1
      source: hpo_holdout_global
  FMDRE:
    hyperparams:
      n_steps: 6400
      lr: 0.0002910898654565733
      batch_size: 512
      precond: false
      time_dist: stiff_inv_40
      reweight: true
      apply_iw: false
      eps: 0.0005988983472138038
      integration_steps: 400
      hidden_dim: 256
      n_shared_layers: 3
      score_weight: 1.0540839311556982
      ema_decay: null
      grad_clip_norm: 5.0
      weight_decay: 0.001
      cosine_min_factor: 0.0
      n_hidden_layers: 5
    score:
      best_value_median: 24.934985160827637
      winner_trial_number: 1820
      best_step: -1
      source: hpo_holdout_global
